In [1]:
import ydf
import pandas as pd

In [2]:
dataset_path="https://raw.githubusercontent.com/google/yggdrasil-decision-forests/main/yggdrasil_decision_forests/test_data/dataset"
dataset =pd.read_csv(f'{dataset_path}/adult_train.csv')
dataset.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,44,Private,228057,7th-8th,4,Married-civ-spouse,Machine-op-inspct,Wife,White,Female,0,0,40,Dominican-Republic,<=50K
1,20,Private,299047,Some-college,10,Never-married,Other-service,Not-in-family,White,Female,0,0,20,United-States,<=50K
2,40,Private,342164,HS-grad,9,Separated,Adm-clerical,Unmarried,White,Female,0,0,37,United-States,<=50K
3,30,Private,361742,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,50,United-States,<=50K
4,67,Self-emp-inc,171564,HS-grad,9,Married-civ-spouse,Prof-specialty,Wife,White,Female,20051,0,30,England,>50K

In [4]:
model =ydf.GradientBoostedTreesLearner(label="income").train(dataset)

Train model on 22792 examples
Model trained in 0:00:02.203368

In [20]:
dataset['race'].value_counts()

race
White                 19467
Black                  2174
Asian-Pac-Islander      727
Amer-Indian-Eskimo      216
Other                   208
Name: count, dtype: int64

In [8]:
dataset['workclass'].value_counts()

workclass
Private             15879
Self-emp-not-inc     1777
Local-gov            1495
State-gov             891
Self-emp-inc          802
Federal-gov           677
Without-pay            11
Never-worked            3
Name: count, dtype: int64

In [9]:
dataset['education'].value_counts()

education
HS-grad         7340
Some-college    5077
Bachelors       3768
Masters         1223
Assoc-voc        978
11th             828
Assoc-acdm       765
10th             656
7th-8th          448
Prof-school      397
9th              354
12th             306
Doctorate        284
5th-6th          216
1st-4th          117
Preschool         35
Name: count, dtype: int64

In [17]:
dataset.loc[dataset['education'] == 'Bachelors']

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
6,51,Private,200618,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,<=50K
7,32,Private,295117,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,40,England,>50K
15,50,Private,171225,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,0,0,40,Philippines,>50K
21,26,NaN,167835,Bachelors,13,Married-civ-spouse,NaN,Wife,White,Female,0,0,20,United-States,<=50K
26,30,Private,118551,Bachelors,13,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,16,United-States,>50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22761,27,State-gov,122660,Bachelors,13,Never-married,Prof-specialty,Own-child,Black,Female,0,0,40,United-States,<=50K
22767,25,Self-emp-inc,90752,Bachelors,13,Never-married,Sales,Not-in-family,White,Female,0,0,50,United-States,<=50K
22769,24,Private,126568,Bachelors,13,Married-civ-spouse,Other-service,Husband,White,Male,0,0,33,United-States,<=50K
22774,42,Private,211253,Bachelors,13,Divorced,Exec-managerial,Unmarried,White,Female,0,0,40,United-States,<=50K
22782,49,Self-emp-not-inc,232664,Bachelors,13,Never-married,Exec-managerial,Own-child,White,Female,0,0,40,United-States,<=50K

In [14]:
dataset.iloc[6,:]

age                               51
workclass                    Private
fnlwgt                        200618
education                  Bachelors
education_num                     13
marital_status    Married-civ-spouse
occupation            Prof-specialty
relationship                 Husband
race                           White
sex                             Male
capital_gain                       0
capital_loss                       0
hours_per_week                    40
native_country         United-States
income                         <=50K
Name: 6, dtype: object

In [21]:
model.predict({'age': [48], 'workclass': ['Self-emp-inc'],
               'fnlwgt': [228057],
               'education': ['Bachelors'], 'education_num':[13], 'marital_status':['Divorced'],'occupation':['Machine-op-inspct'],
               'relationship': ['Wife'], 'race':['Amer-Indian-Eskimo'], 'sex':['Female'], 'capital_gain':[0],
               'capital_loss': [0], 'hours_per_week': [50], 'native_country':['United-States']})

array([0.3008696], dtype=float32)

In [23]:
model.label_classes()[True], model.label_classes()[False]

('>50K', '<=50K')

In [24]:
model.to_docker('ydf_test')

In [25]:
!ls -l ydf_test

total 28
-rw-rw-r-- 1 sam sam  288 Sep  2 16:40 deploy_in_google_cloud.sh
-rw-rw-r-- 1 sam sam  211 Sep  2 16:40 Dockerfile
-rw-rw-r-- 1 sam sam 1313 Sep  2 16:40 main.py
drwxrwxr-x 2 sam sam 4096 Sep  2 16:40 model
-rw-rw-r-- 1 sam sam  360 Sep  2 16:40 readme.txt
-rw-rw-r-- 1 sam sam   26 Sep  2 16:40 requirements.txt
-rw-rw-r-- 1 sam sam  485 Sep  2 16:40 test_locally.sh